### ISSUE TITLE
process for adding plugins?

### ISSUE THREAD

**Issue by shimmerjs** [gocd/gocd-helm-chart#18]

**Comment by GaneshSPatil** [comment]
@booninite -- The GoCD server image stores persistence under `/godata` path of the container.
You can use `persistent volumes` to mount `/godata` directory by specifying [server godata persistence values](https://github.com/gocd/gocd-helm-chart#server-godata-persistence-values).

All the plugins should be installed under `/godata/plugins/` directory.

You can find more information about GoCD Server Docker image configuration [here](https://hub.docker.com/r/gocd/gocd-server/).

**Comment by varshavaradarajan** [comment]
@booninite - we have also provided an option to specify a download url for the plugin. Refer to the `Installing plugins using an environment configuration` in the [documentation](https://hub.docker.com/r/gocd/gocd-server/). By prepending `GO_PLUGIN_INSTALL_` to the plugin name and providing this as an environment variable in `values.yaml` you can start the GoCD server with your plugin using the helm chart.
