### ISSUE TITLE
Shutdown pods gracefully

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd-helm-chart#23]
##### Issue Type
- Feature enhancement

##### Summary

@varshavaradarajan brought this up: "We should do this for the helm chart for agents - https://pracucci.com/graceful-shutdown-of-kubernetes-pods.html. For server, we recreate (instead of rolling update), so, it terminates existing server container, also abruptly, and brings up a new one with the existing config and db. Might result in some db corruption if it terminates abruptly. May be we can have a pre-stop hook to call stop-server.sh instead?"

/cc @sheroy - What do you think?

**Comment by sheroy** [comment]
@arvindsv Yes, I think this is worth introducing for agents. Let's talk about it when someone is ready to pick it up.

**Comment by varshavaradarajan** [comment]
More context about graceful shutdown for agents: https://github.com/gocd/gocd/issues/5218

**Comment by arvindsv** [comment]
I'm not tracking this any more. Leaving with @sheroy and @ankitsri11 to decide and try, if needed.

**Comment by varshavaradarajan** [comment]
I don't think we need to do anything here. So, k8s (like docker stop) sends SIGTERM to process with pid 1, which is tini in our case, which forwards the signal to the child (gocd server or agent bootstrapper process). This is the same as doing `./stop-server.sh`or `./stop-agent.sh` which issues SIGTERM to the server or agent bootstrapper process? Please re-open if needed.

**Comment by varshavaradarajan** [comment]
Sorry, gocd/gocd#5218 needs to be addressed. To provide a pre-stop hook for agents, if not for server. Also, if any script needs to be invoked to backup the db, artifacts, etc before shutting down, a pre stop hook makes sense for that if not to shutdown pods gracefully.

**Comment by varshavaradarajan** [comment]
Closing now because the GoCD Helm chart supports pre-stop hooks to take backups, etc before k8s kills the gocd-server or agent pod. This helps in gracefully shutting down the server and agent.
